name: Lint Code

on: 
  push: 
    branches: [ dev ] 
    paths: 
      - 'app.py' 
      - 'model.py' 
      - 'pylint.py'  # Updated to use pylint.py

jobs: 
  lint: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up Python 3.13 
        uses: actions/setup-python@v2 
        with: 
          python-version: 3.13 

      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install pylint 

      - name: Lint with pylint 
        run: | 
          python pylint.py  # Updated to run pylint.py
